cool

diff --git a/gtfar b/gtfar
--- a/gtfar
+++ b/gtfar
@@ -129,8 +129,10 @@ function second_feature_map {
     MYSEED=$1; MYSUBS=$2; MYREF=$3; MYREADS=$4; TYPE=$5; MYPREFIX=$6; MAPLOG=$7; SAY1=$8
     if ! [ -z "$SAY1" ]; then echo "Mapping reads to "$SAY1" (Iteration 2 )..."; fi 
     perm $MYREF $MYREADS --seed $MYSEED -v $MYSUBS -B -o $MYPREFIX.mapping --printNM -u "$MYPREFIX"_miss.fastq >> $MAPLOG
+    if [ $? != 0 ]; then echo "perm-fail"; exit; fi  
     if ! [ -z "$SAY1" ]; then echo "Parsing alignment..."; fi 
     parse_alignment.py $TYPE $MYPREFIX.mapping -k $KEY -p "$MYPREFIX"_parse 
+    if [ $? != 0 ]; then echo "parse-fail"; exit; fi 
     }
 
 function iterative_feature_analysis {
@@ -140,8 +142,8 @@ function iterative_feature_analysis {
     first_feature_map $SEED1 $SUB1 $EXON_100_F1 $READS --exonic $OUTPUT/exonic1 $MAPLOG 'exonic seqs'
     first_feature_map $SEED1 $SUB1 $INTRON_100_F1 $OUTPUT/exonic1_miss.fastq --intronic $OUTPUT/intronic1 $MYLOG "intronic seqs"
     # ROUND 2 # 
-    second_feature_map $SEED2 $SUB2 $OUTPUT/exonic1_iter_exonSeqs.fa $OUTPUT/intronic1_miss.fastq --exonic $OUTPUT/exonic2 $MYLOG 'exonic seqs' 
-    second_feature_map $SEED2 $SUB2 $OUTPUT/intronic1_iter_intronSeqs.fa $OUTPUT/exonic2_miss.fastq --intronic $OUTPUT/intronic2 $MYLOG 'intron seqs' 
+    second_feature_map $SEED2 $SUB2 $OUTPUT/exonic1_iter1_exonSeqs.fa $OUTPUT/intronic1_miss.fastq --exonic $OUTPUT/exonic2 $MYLOG 'exonic seqs' 
+    second_feature_map $SEED2 $SUB2 $OUTPUT/intronic1_iter1_intronSeqs.fa $OUTPUT/exonic2_miss.fastq --intronic $OUTPUT/intronic2 $MYLOG 'intron seqs' 
     # NOW DO THE TRIMED READS # 
     
     
@@ -155,7 +157,9 @@ function iterative_feature_analysis {
     sort -m -k14n,14 -k6,6 -k8n,8 $OUTPUT/intronic*.srt > $OUTPUT/intronic_iter_gene.srt  
     if ! [ -z "$SAY" ]; then echo "Determining iterative mutations..."; fi 
     call_mutations.py $OUTPUT/exonic_iter_gene.srt $GTF --exonic -g $HG19 -p $OUTPUT/exonic_iterative 
+    if [ $? != 0 ]; then echo "call-fail"; exit; fi 
     call_mutations.py $OUTPUT/intronic_iter_gene.srt $GTF --intronic -g $HG19 -p $OUTPUT/intronic_iterative 
+    if [ $? != 0 ]; then echo "call-fail"; exit; fi 
 
     }
 
@@ -167,9 +171,10 @@ function iterative_feature_analysis {
 function double_genome_map { 
     SEED=$1; SUBS=$2; MYREADS=$3; MYPREFIX=$4; MAPLOG=$5; SAY=$6; 
     if ! [ -z "$SAY" ]; then echo -n "Mapping reads to human genome......"; fi 
-    #echo perm $HG19_100_F2 $MYREADS --seed $SEED -v $SUBS -B -o $MYPREFIX.mapping --printNM -u "$MYPREFIX"_miss.fastq >> $MAPLOG  
+    echo perm $HG19_100_F2 $MYREADS --seed $SEED -v $SUBS -B -o $MYPREFIX.mapping --printNM -u "$MYPREFIX"_miss.fastq >> $MAPLOG  
     perm $HG19_100_F2 $MYREADS --seed $SEED -v $SUBS -B -o $MYPREFIX.mapping --printNM -u "$MYPREFIX"_miss.fastq >> $MAPLOG 
     parse_alignment.py $MYPREFIX.mapping --hg19 -p "$MYPREFIX"_parse 
+    
     perm $HG19_100_F2 $MYREADS --seed $SEED -v $SUBS -B -o $MYPREFIX.sam > "$MYPREFIX"_sam.log
     if [ $? != 0 ]; then echo "perm-fail"; exit; fi  
     if ! [ -z "$SAY" ]; then echo "Complete"; fi 
@@ -183,29 +188,29 @@ function multi_gapped_alignment {
     REF1=$1; REF2=$2; REF3=$3; MYREADS=$4; MYPREFIX=$5; MAPLOG=$6; SAY=$7
     
     if ! [ -z "$SAY" ]; then echo -n "Gapped mapping to concatenated exons....."; fi 
-    clipR $REF1 $MYREADS --anchorL 40 --seed F1 -v 1 --ignoreRepeatR 10 --ignoreDummyR 40 -u "$MYPREFIX"_cat_miss.fastq -o "$MYPREFIX"_cat.sam --noSamHeader >> $MAPLOG  
+#    clipR $REF1 $MYREADS --anchorL 40 --seed F1 -v 1 --ignoreRepeatR 10 --ignoreDummyR 40 -u "$MYPREFIX"_cat_miss.fastq -o "$MYPREFIX"_cat.sam --noSamHeader >> $MAPLOG  
     if [ $? != 0 ]; then echo "clipR-fail"; exit; fi  
     if ! [ -z "$SAY" ]; then echo "Complete"; echo -n "Parsing gapped exonic alignment....."; fi 
     #if ! [ -z "$SAY" ]; then echo -n "Parsing gapped exonic alignment....."; fi 
-    parse_alignment.py "$MYPREFIX"_cat.sam --gapped -k $KEY -p "$MYPREFIX"_cat_parse    
+#    parse_alignment.py "$MYPREFIX"_cat.sam --gapped -k $KEY -p "$MYPREFIX"_cat_parse    
     if [ $? != 0 ]; then echo "Parse-fail"; exit; fi  
     
     if ! [ -z "$SAY" ]; then echo "Complete"; echo -n "Gapped mapping to gene sequences..."; fi 
     #if ! [ -z "$SAY" ]; then echo "Gapped mapping to gene sequences"; fi 
-    clipR $REF2 "$MYPREFIX"_cat_miss.fastq --anchorL 40 --seed F1 -v 1 --ignoreRepeatR 10 --ignoreDummyR 40 -u "$MYPREFIX"_gene_miss.fastq -o "$MYPREFIX"_gene.sam --noSamHeader >> $MAPLOG 
+#    clipR $REF2 "$MYPREFIX"_cat_miss.fastq --anchorL 40 --seed F1 -v 1 --ignoreRepeatR 10 --ignoreDummyR 40 -u "$MYPREFIX"_gene_miss.fastq -o "$MYPREFIX"_gene.sam --noSamHeader >> $MAPLOG 
     if [ $? != 0 ]; then echo "clipR-fail"; exit; fi  
     if ! [ -z "$SAY" ]; then echo "Complete"; echo -n "Parsing gapped gene alignment....."; fi 
     #if ! [ -z "$SAY" ]; then echo "Parsing gapped gene alignment"; fi 
-    parse_alignment.py "$MYPREFIX"_gene.sam --gapped -k $KEY -p "$MYPREFIX"_gene_parse    
+#    parse_alignment.py "$MYPREFIX"_gene.sam --gapped -k $KEY -p "$MYPREFIX"_gene_parse    
     if [ $? != 0 ]; then echo "Parse-fail"; exit; fi  
     
     #if ! [ -z "$SAY" ]; then echo "Gapped mapping to human genome....."; fi 
     if ! [ -z "$SAY" ]; then echo "Complete"; echo -n "Gapped mapping to human genome..."; fi 
-    clipR $REF3 "$MYPREFIX"_gene_miss.fastq --anchorL 40 --seed F1 -v 1 --ignoreRepeatR 10 --ignoreDummyR 40 -u "$MYPREFIX"_hg19_miss.fastq -o "$MYPREFIX"_hg19.sam --noSamHeader >> $MAPLOG  
+    echo "clipR $REF3 "$MYPREFIX"_gene_miss.fastq --anchorL 40 --seed F1 -v 1 --ignoreRepeatR 10 --ignoreDummyR 40 -u "$MYPREFIX"_hg19_miss.fastq -o "$MYPREFIX"_hg19.sam --noSamHeader >> $MAPLOG  "
     if [ $? != 0 ]; then echo "clipR-fail"; exit; fi  
     if ! [ -z "$SAY" ]; then echo "Complete"; echo -n "Parsing gapped genomic alignment....."; fi 
     #if ! [ -z "$SAY" ]; then echo "Parsing gapped genomic alignment"; fi 
-    parse_alignment.py "$MYPREFIX"_hg19.sam --hg19 -k $KEY -p "$MYPREFIX"_hg19_parse    
+#    parse_alignment.py "$MYPREFIX"_hg19.sam --hg19 -k $KEY -p "$MYPREFIX"_hg19_parse    
     if ! [ -z "$SAY" ]; then echo "Complete"; fi 
     }
 
@@ -223,15 +228,17 @@ if [ $PROGRAM == "iter-map" ] || [ $PROGRAM == "ITER-MAP" ]; then
         echo "Pipeline Begins Sample: " $READS
 
 
-        iterative_feature_analysis F1 2 F3 5 $MYLOG GO
+        #iterative_feature_analysis F1 2 F3 5 $MYLOG GO
 
         # GENOMIC ALIGNMENT (TWO FILETYPES) #
-        double_genome_map F2 4 $OUTPUT/intronic2_miss.fastq $OUTPUT/hg19 $MYLOG GO 
+        #double_genome_map F2 4 $OUTPUT/intronic2_miss.fastq $OUTPUT/hg19 $MYLOG GO 
         
         
         # GAPPED ALIGNMENT - MULTIPLE WAYS #
 
         multi_gapped_alignment $OUTPUT/exonic_iterative_catsOnly.fa $OUTPUT/exonic_iterative_geneSeqs.fa $HG19CLIP_40_F1 $OUTPUT/hg19_miss.fastq $OUTPUT/GAPS $MYLOG GO 
+        exit
+        
         cp $OUTPUT/GAPS_hg19_miss.fastq $OUTPUT/"$PREFIX_"remainingReads.fq
         echo "MAPPING COMPLETE"
         echo ""
@@ -256,13 +263,13 @@ if [ $PROGRAM == "iter-map" ] || [ $PROGRAM == "ITER-MAP" ]; then
         # MERGE EXPRESSION, ETC, ETC, ETC # --- ALSO YOU COULD PARSE THE GENOME BETTER  
         
         cat $OUTPUT/*gene.cnts | sort -k1,1 -k5,5 | awk '{if ($5!=L) {if (NR!=1) print A,B,C,"|",L,X,Y,Z; A=$1;B=$2;C=$3;L=$5;X=$6;Y=$7;Z=$8} else {X+=$6;Y+=$7;Z+=$8}} END{print A,B,C,"|",L,X,Y,Z}' > $RESULTS/$PREFIX.gene.cnts
-        mv $OUTPUT/*gene.cnts $OUTPUT/tmp/
+        mv $OUTPUT/*gene.cnts $TEMP/
 
         # MERGE TRANSCRIPT & INTRON COUNTS #
         
         cat $OUTPUT/exonic*_feat.cnts | sort -k1,1 | awk '{if ($1==L) C+=$3; else {if (NR>1) print L,T,C; L=$1;T=$2;C=$3}} END{print L,T,C}' > $RESULTS/$PREFIX.exonicFeature.cnts &
         cat $OUTPUT/intronic*feat.cnts | sort -k1,1 | awk '{if ($1==L) C+=$3; else {if (NR>1) print L,T,C; L=$1;T=$2;C=$3}} END{print L,T,C}' > $RESULTS/$PREFIX.intronicFeature.cnts &
-        mv *feat.cnts tmp/
+        mv $OUTPUT/*feat.cnts $TEMP/
 
         # CLEANUP MUTATIONS #
 
