semi-stable

diff --git a/gtfar b/gtfar
--- a/gtfar
+++ b/gtfar
@@ -18,6 +18,7 @@ HGREF=/export/uec-gs1/knowles/analysis/tade/references_and_annotation/human/hg19
 
 GTF=/export/uec-gs1/knowles/analysis/tade/references_and_annotation/human/gencode16/gencode.v16.annotation.gtf
 DATA=/export/uec-gs1/knowles/analysis/tade/references_and_annotation/human/gencode16/annotation_data
+KEY=$DATA/gc16.key
 
 INDEXES=/export/uec-gs1/knowles/analysis/tade/references_and_annotation/human/indexes
 GC16_IDXS=/export/uec-gs1/knowles/analysis/tade/references_and_annotation/human/indexes/gc16
@@ -84,13 +85,88 @@ else mkdir $OUTPUT; fi
 
 
 
-#####################################################  TOOLS            ###################################################################3
 
-function smart_move {
-    WC=(*$1)
-    if [ -e ${WC[0]} ]; then
-        mv *$1 $2/
+
+######################################################  MAPPING/PARSING   #################################################################################
+
+
+function exonic_map_and_parse {
+
+    ITER=$1; MYREADS=$2; MYREF=$3
+
+    if [ $ITER -eq 1 ]; then
+        echo  "Mapping reads to exonic seqs (iteration 1)..." 
+        perm $EXON_100_F1 $MYREADS --seed F1 -v 2 -B -o exonic1.mapping -u exonic1_miss.fastq --printNM >> MAP.log
+        if [ $? != 0 ]; then echo "perm-fail"; exit; fi  
+        parse_alignment.py exonic1.mapping -k $KEY --ref=exonic --verbose -p exonic1 --strand - 
+        if [ $? != 0 ]; then echo "parse-fail"; exit; fi 
+        call_mutations.py exonic1_gene.srt $GTF -g $HG19 -p exonic1 --ref=exonic --annotate --verbose
+        if [ $? != 0 ]; then echo "call-fail"; exit; fi 
+    elif [ $ITER -eq 2 ]; then
+        echo  "Mapping reads to exonic seqs (iteration 2)..." 
+        perm exonic1_exonSeqs.fa $MYREADS --seed F3 -v 5 -B -o exonic2.mapping -u exonic2_miss.fastq --printNM >> MAP.log
+        if [ $? != 0 ]; then echo "perm-fail"; exit; fi  
+        parse_alignment.py exonic2.mapping -k $KEY --ref=exonic -p exonic2 --verbose --strand -
+        if [ $? != 0 ]; then echo "parse-fail"; exit; fi  
+        sort -m -k14n,14 -k6,6 -k8n,8 exonic1_gene.srt exonic2_gene.srt > exonic_iter_gene.srt
+         call_mutations.py exonic_iter_gene.srt $GTF --ref=exonic -g $HG19 -p exonic_iterative --annotate --verbose
+        if [ $? != 0 ]; then echo "call-fail"; exit; fi 
     fi
+}
+
+
+function intronic_map_and_parse {
+
+    ITER=$1; MYREADS=$2; MYREF=$3
+    if [ $ITER -eq 1 ]; then
+        echo  "Mapping reads to intronic seqs (iteration 1)..." 
+        perm $INTRON_100_F1 $MYREADS --seed F1 -v 2 -B -o intronic1.mapping -u intronic1_miss.fastq --printNM >> MAP.log
+        if [ $? != 0 ]; then echo "perm-fail"; exit; fi  
+        parse_alignment.py intronic1.mapping -k $KEY --ref=intronic -p intronic1 --verbose --strand -
+        if [ $? != 0 ]; then echo "parse-fail"; exit; fi 
+        call_mutations.py intronic1_gene.srt $GTF --ref=intronic -g $HG19 -p intronic1 --annotate --verbose
+        if [ $? != 0 ]; then echo "call-fail"; exit; fi 
+    elif [ $ITER -eq 2 ]; then
+        echo  "Mapping reads to intronic seqs (iteration 2)..." 
+        perm intronic1_intronSeqs.fa $MYREADS --seed F3 -v 5 -B -o intronic2.mapping -u intronic2_miss.fastq --printNM >> MAP.log
+        if [ $? != 0 ]; then echo "perm-fail"; exit; fi  
+        parse_alignment.py intronic2.mapping -k $KEY --ref=intronic -p intronic2 --verbose --strand -
+        if [ $? != 0 ]; then echo "parse-fail"; exit; fi 
+        sort -m -k14n,14 -k6,6 -k8n,8 intronic1_gene.srt intronic2_gene.srt > intronic_iter_gene.srt
+        call_mutations.py intronic_iter_gene.srt $GTF --ref=intronic -g $HG19 -p intronic_iterative --annotate --verbose
+        if [ $? != 0 ]; then echo "call-fail"; exit; fi 
+    fi
+}
+
+function genome_map_and_parse {
+
+    MYREADS=$1 
+    echo "Mapping reads to human genome......"
+    perm $HG19_100_F2 $MYREADS --seed F2 -v 4 -B -o hg.mapping --printNM -u hg_miss.fastq >> MAP.log 
+    perm $HG19_100_F2 $MYREADS --seed F2 -v 4 -B -o hg.sam > /dev/null
+    if [ $? != 0 ]; then echo "perm-fail"; exit; fi  
+    parse_alignment.py hg.mapping -k $KEY --ref=genomic -p hg --verbose  
+    }
+
+
+function multiple_gapped_alignment {
+
+    MYREADS=$1
+    
+    echo -n "Performed Gapped Mapping to exons/genes/genome......"
+    clipR $CATCLIP_40_F1 $MYREADS --anchorL 40 --seed F1 -v 1 --ignoreRepeatR 10 --ignoreDummyR 45 -u catclip_miss.fastq -o cat_gap.sam --noSamHeader >> MAP.log 
+    echo -n "......"
+    clipR $GENECLIP_40_F1 catclip_miss.fastq --anchorL 40 --seed F1 -v 1 --ignoreRepeatR 10 --ignoreDummyR 45 -u geneclip_miss.fastq -o gene_gap.sam --noSamHeader >> MAP.log 
+    echo -n "......"
+    clipR $HG19CLIP_40_F1 geneclip_miss.fastq --anchorL 40 --seed F1 -v 4 --ignoreRepeatR 10 --ignoreDummyR 40 -u remaining_reads.fq -o hg_gap_vis.sam --noSamHeader >> MAP.log 
+    if [ $? != 0 ]; then echo "clipR-fail"; exit; else echo "Complete"; fi 
+
+    ## PARSING ##
+
+    parse_alignment.py cat_gap.sam  -k $KEY --ref=exonic  -p cat_gap  --gapped  --verbose 
+    parse_alignment.py gene_gap.sam -k $KEY --ref=genes   -p gene_gap --gapped  --verbose 
+    parse_alignment.py hg_gap_vis.sam   -k $KEY --ref=genomic -p hg_gap   --gapped  --verbose 
+
 }
 
 
@@ -98,244 +174,61 @@ function smart_move {
 
 
 
+if [ $PROGRAM == 'test' ]; then 
+   
+    echo "GTFAR-Pipeline Verson 0.0.03"
+    echo "GtfFile: "$GTF
+    echo "Reads:   "$READS
+    echo "Output:  "$OUTPUT    
+    echo ""
 
+    ## MAPPING TO MAJOR ANNOTATIONS ##
 
+    exonic_map_and_parse 1 $READS   
+    intronic_map_and_parse 1 exonic1_miss.fastq 
+    exonic_map_and_parse 2 intronic1_miss.fastq
+    intronic_map_and_parse 2 exonic2_miss.fastq 
 
-
-
-
-
-
-
-######################################################  FEATURE MAPPING   #################################################################################
-
-function first_feature_map {
-       
-    MYSEED=$1; MYSUBS=$2; MYREF=$3; MYREADS=$4; TYPE=$5; MYPREFIX=$6; MAPLOG=$7; SAY1=$8;
-        
-    if ! [ -z "$SAY1" ]; then echo  "Mapping reads to "$SAY1" (Iteration 1 )..."; fi 
-    perm $MYREF $MYREADS --seed $MYSEED -v $MYSUBS -B -o $MYPREFIX.mapping --printNM -u "$MYPREFIX"_miss.fastq >> $MAPLOG
-    if [ $? != 0 ]; then echo "perm-fail"; exit; fi  
-    if ! [ -z "$SAY1" ]; then echo "Parsing alignment..."; fi 
-    parse_alignment.py $TYPE $MYPREFIX.mapping -k $KEY -p "$MYPREFIX"_parse 
-    if [ $? != 0 ]; then echo "parse-fail"; exit; fi 
-    if ! [ -z "$SAY1" ]; then echo "Determining mutations"...; fi 
-    call_mutations.py "$MYPREFIX"_parse_gene.srt $GTF $TYPE -g $HG19 -p "$MYPREFIX"_iter1 
-    if [ $? != 0 ]; then echo "call-fail"; exit; fi 
-    if ! [ -z "$SAY1" ]; then echo "Complete"; echo ""; fi 
-    }
-
-function second_feature_map {   
-    MYSEED=$1; MYSUBS=$2; MYREF=$3; MYREADS=$4; TYPE=$5; MYPREFIX=$6; MAPLOG=$7; SAY1=$8
-    if ! [ -z "$SAY1" ]; then echo "Mapping reads to "$SAY1" (Iteration 2 )..."; fi 
-    perm $MYREF $MYREADS --seed $MYSEED -v $MYSUBS -B -o $MYPREFIX.mapping --printNM -u "$MYPREFIX"_miss.fastq >> $MAPLOG
-    if [ $? != 0 ]; then echo "perm-fail"; exit; fi  
-    if ! [ -z "$SAY1" ]; then echo "Parsing alignment..."; fi 
-    parse_alignment.py $TYPE $MYPREFIX.mapping -k $KEY -p "$MYPREFIX"_parse 
-    if [ $? != 0 ]; then echo "parse-fail"; exit; fi 
-    }
-
-function iterative_feature_analysis {
-
-    SEED1=$1; SUB1=$2; SEED2=$3; SUB2=$4; MAPLOG=$5; SAY=$6
-    # ROUND 1 # 
-    first_feature_map $SEED1 $SUB1 $EXON_100_F1 $READS --exonic $OUTPUT/exonic1 $MAPLOG 'exonic seqs'
-    first_feature_map $SEED1 $SUB1 $INTRON_100_F1 $OUTPUT/exonic1_miss.fastq --intronic $OUTPUT/intronic1 $MYLOG "intronic seqs"
-    # ROUND 2 # 
-    second_feature_map $SEED2 $SUB2 $OUTPUT/exonic1_iter1_exonSeqs.fa $OUTPUT/intronic1_miss.fastq --exonic $OUTPUT/exonic2 $MYLOG 'exonic seqs' 
-    second_feature_map $SEED2 $SUB2 $OUTPUT/intronic1_iter1_intronSeqs.fa $OUTPUT/exonic2_miss.fastq --intronic $OUTPUT/intronic2 $MYLOG 'intron seqs' 
-    # NOW DO THE TRIMED READS # 
+    ### MAPPING TO HG 19 ###
     
-    
-    # COMBINE ANALYSIS # 
+    genome_map_and_parse intronic2_miss.fastq
+   
+    ### GAPPED MAPPING ### 
 
-    # 
+    multiple_gapped_alignment hg_miss.fastq
 
+    echo "MAPPING-COMPLETE"
 
-    if ! [ -z "$SAY" ]; then echo "Combining/mergeing iterative results..."; fi 
-    sort -m -k14n,14 -k6,6 -k8n,8 $OUTPUT/exonic*.srt >   $OUTPUT/exonic_iter_gene.srt 
-    sort -m -k14n,14 -k6,6 -k8n,8 $OUTPUT/intronic*.srt > $OUTPUT/intronic_iter_gene.srt  
-    if ! [ -z "$SAY" ]; then echo "Determining iterative mutations..."; fi 
-    call_mutations.py $OUTPUT/exonic_iter_gene.srt $GTF --exonic -g $HG19 -p $OUTPUT/exonic_iterative 
-    if [ $? != 0 ]; then echo "call-fail"; exit; fi 
-    call_mutations.py $OUTPUT/intronic_iter_gene.srt $GTF --intronic -g $HG19 -p $OUTPUT/intronic_iterative 
-    if [ $? != 0 ]; then echo "call-fail"; exit; fi 
+    parse_log.py MAP.log
 
-    }
+    if [ ! -d tmp ]; then mkdir tmp; fi
+    mv *.* tmp/
 
-###########################################################################################################################################################################
+    echo ""; echo 'Analyzing Results/Creating Bam File'
 
+    cat tmp/*gene.cnts | sort -k1,1 -k5,5 | awk '{if ($5!=L) {if (NR!=1) print A,B,C,"|",L,X,Y,Z; A=$1;B=$2;C=$3;L=$5;X=$6;Y=$7;Z=$8} else {X+=$6;Y+=$7;Z+=$8}} END{print A,B,C,"|",L,X,Y,Z}' > $PREFIX.gene.cnts
+    cat tmp/*_iterative.mutations > $PREFIX.mutations
+    cat tmp/intronic*_feat.cnts | sort -k1,1 | awk '{if ($1==L) C+=$3; else {if (NR>1) print L,T,C; L=$1;T=$2;C=$3}} END{print L,T,C}' > $PREFIX.intronCnts
+    cat tmp/intronic*splice.cnts | sort -k1,1 | awk '{if ($1==L) C+=$3; else {if (NR>1) print L,T,C; L=$1;T=$2;C=$3}} END{print L,T,C}' > $PREFIX.intEx.jxns &
+    cat tmp/exonic*splice.cnts | sort -k1,1 | awk '{if ($1==L) C+=$3; else {if (NR>1) print L,T,C; L=$1;T=$2;C=$3}} END{print L,T,C}' > $PREFIX.canonical.splices
+    cat tmp/*gap_splice.cnts | sort -k1,1 > $PREFIX.non-canonical.splices
+    mv tmp/*novelAreas.cnts > $PREFIX.novelAreas.cnts
 
+    cat tmp/hg.sam tmp/*_vis.sam > $PREFIX.sam
+    samtools view -bS -o $PREFIX.bam $PREFIX.sam 
+    samtools sort $PREFIX.bam "$PREFIX"_sort
+    samtools index "$PREFIX"_sort.bam 
 
+    if [ $? == 0 ]; then echo "Pipeline Complete Successfully"; exit; fi
 
-function double_genome_map { 
-    SEED=$1; SUBS=$2; MYREADS=$3; MYPREFIX=$4; MAPLOG=$5; SAY=$6; 
-    if ! [ -z "$SAY" ]; then echo -n "Mapping reads to human genome......"; fi 
-    echo perm $HG19_100_F2 $MYREADS --seed $SEED -v $SUBS -B -o $MYPREFIX.mapping --printNM -u "$MYPREFIX"_miss.fastq >> $MAPLOG  
-    perm $HG19_100_F2 $MYREADS --seed $SEED -v $SUBS -B -o $MYPREFIX.mapping --printNM -u "$MYPREFIX"_miss.fastq >> $MAPLOG 
-    parse_alignment.py $MYPREFIX.mapping --hg19 -p "$MYPREFIX"_parse 
-    
-    perm $HG19_100_F2 $MYREADS --seed $SEED -v $SUBS -B -o $MYPREFIX.sam > "$MYPREFIX"_sam.log
-    if [ $? != 0 ]; then echo "perm-fail"; exit; fi  
-    if ! [ -z "$SAY" ]; then echo "Complete"; fi 
-    
-    }
-
-
-
-function multi_gapped_alignment {
-
-    REF1=$1; REF2=$2; REF3=$3; MYREADS=$4; MYPREFIX=$5; MAPLOG=$6; SAY=$7
-    
-    if ! [ -z "$SAY" ]; then echo -n "Gapped mapping to concatenated exons....."; fi 
-#    clipR $REF1 $MYREADS --anchorL 40 --seed F1 -v 1 --ignoreRepeatR 10 --ignoreDummyR 40 -u "$MYPREFIX"_cat_miss.fastq -o "$MYPREFIX"_cat.sam --noSamHeader >> $MAPLOG  
-    if [ $? != 0 ]; then echo "clipR-fail"; exit; fi  
-    if ! [ -z "$SAY" ]; then echo "Complete"; echo -n "Parsing gapped exonic alignment....."; fi 
-    #if ! [ -z "$SAY" ]; then echo -n "Parsing gapped exonic alignment....."; fi 
-#    parse_alignment.py "$MYPREFIX"_cat.sam --gapped -k $KEY -p "$MYPREFIX"_cat_parse    
-    if [ $? != 0 ]; then echo "Parse-fail"; exit; fi  
-    
-    if ! [ -z "$SAY" ]; then echo "Complete"; echo -n "Gapped mapping to gene sequences..."; fi 
-    #if ! [ -z "$SAY" ]; then echo "Gapped mapping to gene sequences"; fi 
-#    clipR $REF2 "$MYPREFIX"_cat_miss.fastq --anchorL 40 --seed F1 -v 1 --ignoreRepeatR 10 --ignoreDummyR 40 -u "$MYPREFIX"_gene_miss.fastq -o "$MYPREFIX"_gene.sam --noSamHeader >> $MAPLOG 
-    if [ $? != 0 ]; then echo "clipR-fail"; exit; fi  
-    if ! [ -z "$SAY" ]; then echo "Complete"; echo -n "Parsing gapped gene alignment....."; fi 
-    #if ! [ -z "$SAY" ]; then echo "Parsing gapped gene alignment"; fi 
-#    parse_alignment.py "$MYPREFIX"_gene.sam --gapped -k $KEY -p "$MYPREFIX"_gene_parse    
-    if [ $? != 0 ]; then echo "Parse-fail"; exit; fi  
-    
-    #if ! [ -z "$SAY" ]; then echo "Gapped mapping to human genome....."; fi 
-    if ! [ -z "$SAY" ]; then echo "Complete"; echo -n "Gapped mapping to human genome..."; fi 
-    echo "clipR $REF3 "$MYPREFIX"_gene_miss.fastq --anchorL 40 --seed F1 -v 1 --ignoreRepeatR 10 --ignoreDummyR 40 -u "$MYPREFIX"_hg19_miss.fastq -o "$MYPREFIX"_hg19.sam --noSamHeader >> $MAPLOG  "
-    if [ $? != 0 ]; then echo "clipR-fail"; exit; fi  
-    if ! [ -z "$SAY" ]; then echo "Complete"; echo -n "Parsing gapped genomic alignment....."; fi 
-    #if ! [ -z "$SAY" ]; then echo "Parsing gapped genomic alignment"; fi 
-#    parse_alignment.py "$MYPREFIX"_hg19.sam --hg19 -k $KEY -p "$MYPREFIX"_hg19_parse    
-    if ! [ -z "$SAY" ]; then echo "Complete"; fi 
-    }
-
-
-    
-
-if [ $PROGRAM == "iter-map" ] || [ $PROGRAM == "ITER-MAP" ]; then 
-
-        # ---- MAP STEP -----  #
-
-        MYLOG=$OUTPUT/MAPPING.stats 
-
-        # ITERATIVE FEATURE ALIGNMENT # 
-
-        echo "Pipeline Begins Sample: " $READS
-
-
-        #iterative_feature_analysis F1 2 F3 5 $MYLOG GO
-
-        # GENOMIC ALIGNMENT (TWO FILETYPES) #
-        #double_genome_map F2 4 $OUTPUT/intronic2_miss.fastq $OUTPUT/hg19 $MYLOG GO 
-        
-        
-        # GAPPED ALIGNMENT - MULTIPLE WAYS #
-
-        multi_gapped_alignment $OUTPUT/exonic_iterative_catsOnly.fa $OUTPUT/exonic_iterative_geneSeqs.fa $HG19CLIP_40_F1 $OUTPUT/hg19_miss.fastq $OUTPUT/GAPS $MYLOG GO 
-        exit
-        
-        cp $OUTPUT/GAPS_hg19_miss.fastq $OUTPUT/"$PREFIX_"remainingReads.fq
-        echo "MAPPING COMPLETE"
-        echo ""
-
-        parse_log.py $MYLOG 
-
-        if  [ ! -d $OUTPUT/results ]; then mkdir $OUTPUT/results;  fi
-        if  [ ! -d $OUTPUT/tmp     ]; then mkdir $OUTPUT/tmp;  fi
-
-        RESULTS=$OUTPUT/results
-        TEMP=$OUTPUT/tmp
-
-        ## CLEANUP ROUND ##
-
-        cd $OUTPUT 
-        smart_move .mapping tmp
-        smart_move .fa      tmp
-        smart_move .log     tmp
-        smart_move .loc     tmp
-        smart_move .fastq  tmp
-        cd ..
-        # MERGE EXPRESSION, ETC, ETC, ETC # --- ALSO YOU COULD PARSE THE GENOME BETTER  
-        
-        cat $OUTPUT/*gene.cnts | sort -k1,1 -k5,5 | awk '{if ($5!=L) {if (NR!=1) print A,B,C,"|",L,X,Y,Z; A=$1;B=$2;C=$3;L=$5;X=$6;Y=$7;Z=$8} else {X+=$6;Y+=$7;Z+=$8}} END{print A,B,C,"|",L,X,Y,Z}' > $RESULTS/$PREFIX.gene.cnts
-        mv $OUTPUT/*gene.cnts $TEMP/
-
-        # MERGE TRANSCRIPT & INTRON COUNTS #
-        
-        cat $OUTPUT/exonic*_feat.cnts | sort -k1,1 | awk '{if ($1==L) C+=$3; else {if (NR>1) print L,T,C; L=$1;T=$2;C=$3}} END{print L,T,C}' > $RESULTS/$PREFIX.exonicFeature.cnts &
-        cat $OUTPUT/intronic*feat.cnts | sort -k1,1 | awk '{if ($1==L) C+=$3; else {if (NR>1) print L,T,C; L=$1;T=$2;C=$3}} END{print L,T,C}' > $RESULTS/$PREFIX.intronicFeature.cnts &
-        mv $OUTPUT/*feat.cnts $TEMP/
-
-        # CLEANUP MUTATIONS #
-
-        cat $OUTPUT/*iterative.mutations > $RESULTS/$PREFIX.mutations
-        mv $OUTPUT/*.mutations $TEMP/
-
-        # CLEANUP SPLICES # 
-
-        cat $OUTPUT/intronic*splice.cnts | sort -k1,1 | awk '{if ($1==L) C+=$3; else {if (NR>1) print L,T,C; L=$1;T=$2;C=$3}} END{print L,T,C}' > $RESULTS/$PREFIX.intEx.jxns &
-        cat $OUTPUT/exonic*splice.cnts | sort -k1,1 | awk '{if ($1==L) C+=$3; else {if (NR>1) print L,T,C; L=$1;T=$2;C=$3}} END{print L,T,C}' > $RESULTS/$PREFIX.canonical.splices
-        cat $OUTPUT/GAPS_*splice.cnts | sort -k1,1 > $RESULTS/$PREFIX.non-canonical.splices
-        mv $OUTPUT/*_splice.cnts $TEMP/
-
-
-        # CLEANUP SORTS # 
-        
-        mv $OUTPUT/*gene.srt $TEMP/
-        
-        # MAKE A BAM FILE #
-        
-        cat $OUTPUT/hg*sam $OUTPUT/*_parse_vis.sam > $OUTPUT/"$PREFIX"_full.sam
-        MYSAM=$OUTPUT/"$PREFIX"_full.sam
-        samtools view -S $MYSAM > $OUTPUT/"$PREFIX"_.bam 
-        samtools sort $OUTPUT/"$PREFIX"_.bam $OUTPUT/"$PREFIX"_sort
-        samtools index $OUTPUT/"$PREFIX"_sort.bam
-        mv $OUTPUT/*.sam $TEMP/ 
-    fi
-
-
-exit
-
-
-
-
-        ###  MERGING FILES FOR MUTATION CALLING ###
-
-   #     sort -m -k14n,14 -k6,6 -k8n,8 $OUTPUT/ex*.srt > $OUTPUT/exJoin_parse_gene.srt 
-   #     sort -m -k14n,14 -k6,6 -k8n,8 $OUTPUT/int*.srt > $OUTPUT/intJoin_parse_gene.srt 
-   #     call_mutations.py output/exJoin_parse_gene.srt  $GTF --exonic    -g $HG19 -p $OUTPUT/exonic_iterative
-   #     call_mutations.py output/intJoin_parse_gene.srt $GTF --intronic -g $HG19 -p $OUTPUT/intronic_iterative
-
-        ### USED MERGE FILES FOR GAPPED ALIGNMENT ###
-
-        echo "Begin Gapped Alignment"
-
-   #     clipR $OUTPUT/exonic_iterative_catsOnly.fa $OUTPUT/miss_round2.fq -o $OUTPUT/gapped_exonic.sam --noSamHeader -e --anchorL 22 --seed F1 -e -v 4 -s $OUTPUT/clipSeq.idx -u $OUPUT/clipMiss.fq --ignoreRepeatR 15 --ignoreDummyR 40 > $OUTPUT/clip.log
-
-
-#ex1_iter_catsOnly.fa  ex1_iter_exonSeqs.fa  int1_iter_intronSeqs.fa
-
-
-
-    fi
-exit 
+    cd ..
+    exit
+fi
 
 
 
 
 
-if [ -d reads ]; then echo "WARNING: reads directory already exists; Files may be overwritten"
-else mkdir reads; fi
-if [ -d refs ]; then echo "WARNING: refs directory  already exists; Files may be overwritten"
-else mkdir refs; fi 
-if [ -d maps ]; then echo "WARNING: maps directory  already exists; Files may be overwritten"
-else mkdir maps; fi
-if [ -d logs ]; then echo "WARNING: maps directory  already exists; Files may be overwritten"
-else mkdir logs; fi
+
 
 
